import '~/features/auth/init'
import '~/features/search/init'
import '~/features/weather/init'
import '~/features/cities/init'
import '~/pages/home/init'
import '~/pages/add/init'
import '~/pages/details/init'
